### PR TITLE
ArrayIndexOutOfBoundsException

### PR DESCRIPTION
**Pull request by rajendrachauhan**
Hi,
        i am Rajendrakumar android developer. so in my app same code i used then will come
some time generate the error of this file when load the AppInstall Ad.

Thank you.
Rajendrakumar

### CODE REVIEW

**Comment by rajendrachauhan** [comment]
I signed it!

**Comment by rajendrachauhan** [comment]
thank you  for verify in CLA

**Comment by stowy** [comment]
Hi @rajendrachauhan, thanks for your contribution.

I'm wondering if this fix is needed, due to the comment:
`// At least one image is guaranteed.`

Can you provide an example of how to reproduce the crash? If it is needed we will need to do for content ads also.

**Comment by rajendrachauhan** [comment]
// At least one image is guaranteed. but in live key (id) of native advance not working and i had generated many crashes for that and i put above code with condition for made changed so right now i have no any crashes generate in my app. and i put my crashes code below :
IndexOutOfBoundsException: 
  at java.util.ArrayList.throwIndexOutOfBoundsException (ArrayList.java:255)
  at java.util.ArrayList.get (ArrayList.java:308)
  at populateAppInstallAdView () of this method call

**Comment by stowy** [comment]
I'm ok to accept this PR, but I'd like to change all occurrences in the examples, see [this search for all occurrences](https://github.com/googleads/googleads-mobile-android-examples/search?utf8=%E2%9C%93&q=%22%2F%2F+At+least+one+image+is+guaranteed%22&type=).

If you're happy to change all three to check the array size, also please remove the comment `// At least one image is guaranteed` in each location, and I will approve.

**Comment by stowy** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
